config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  resources :job_offers do
    get 'user_offers', on: :collection
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  post 'users/associate_job_offer/:job_offer_id', to: 'job_offers#associate_job_offer', as: 'associate_job_offer'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # Ruta raíz para usuarios no autenticados
  root to: 'pages#home', constraints: ->(req) { !req.env['warden'].user }

  # Ruta raíz para usuarios autenticados
  authenticated :user do
    root to: 'job_offers#index', as: :authenticated_root
  end
end

app/models/job_offer.rb
class JobOffer < ApplicationRecord
    has_and_belongs_to_many :users
end

app/controllers/job_offers_controller.rb
class JobOffersController < ApplicationController
  before_action :set_job_offer, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :authorize_admin, only: [:new, :create, :destroy, :edit, :update]
  before_action :only_normal_users, only: [:user_offers, :associate_job_offer]

  # GET /job_offers or /job_offers.json
  def index
    @job_offers = JobOffer.all
  end

  # GET /job_offers/1 or /job_offers/1.json
  def show
  end

  # GET /job_offers/new
  def new
    @job_offer = JobOffer.new
  end

  # GET /job_offers/1/edit
  def edit
  end

  # POST /job_offers or /job_offers.json
  def create
    @job_offer = JobOffer.new(job_offer_params)

    respond_to do |format|
      if @job_offer.save
        format.html { redirect_to job_offer_url(@job_offer), notice: "Job offer was successfully created." }
        format.json { render :show, status: :created, location: @job_offer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_offers/1 or /job_offers/1.json
  def update
    respond_to do |format|
      if @job_offer.update(job_offer_params)
        format.html { redirect_to job_offer_url(@job_offer), notice: "Job offer was successfully updated." }
        format.json { render :show, status: :ok, location: @job_offer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_offers/1 or /job_offers/1.json
  def destroy
    @job_offer.destroy

    respond_to do |format|
      format.html { redirect_to job_offers_url, notice: "Job offer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # Users jobs offers
  def user_offers
  end

  def associate_job_offer
    @user = current_user
    @job_offer = JobOffer.find(params[:job_offer_id])
    
    if @user.job_offers.include?(@job_offer)
      flash[:notice] = "Ya has postulado a esta oferta de trabajo."
      redirect_to user_offers_job_offers_path
    else
      @user.job_offers << @job_offer
      flash[:notice] = "Has postulado exitosamente a la oferta de trabajo."
      redirect_to user_offers_job_offers_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_offer
      @job_offer = JobOffer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_offer_params
      params.require(:job_offer).permit(:job, :description)
    end

    def authorize_admin
      unless current_user.admin?
        redirect_to root_path, alert: 'Solo los administradores pueden añadir nuevas ofertas laborales.'
      end
    end

    def only_normal_users
      if current_user.admin?
        redirect_to root_path, alert: 'Solo los usuarios pueden postular a ofertas laborales.'
      end
    end
end

app/helpers/job_offers_helper.rb
module JobOffersHelper
end

app/views/job_offers/_form.html.erb
<%= form_with(model: job_offer) do |form| %>
  <% if job_offer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job_offer.errors.count, "error") %> prohibited this job_offer from being saved:</h2>

      <ul>
        <% job_offer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :job, "Puesto de trabajo", class: "form-label mb-2" %>
    <%= form.text_field :job, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :description, "Descripción", class: "form-label mb-2" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="mb-5">
    <%= form.submit "Publicar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/job_offers/_job_offer.html.erb
<div id="<%= dom_id job_offer %>">
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h3 class="card-title"><strong><%= job_offer.job %></strong></h3>
      <p class="card-text"><%= job_offer.description %></p>
      <div class="d-flex justify-content-end">
        <%= link_to "Ver más", job_offer, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/job_offers/edit.html.erb
<div class="row">
  <div class="col-lg-3"></div>
  <div class="col-lg-6">
    <h2 class="mb-4">Editando...</h2>

    <%= render "form", job_offer: @job_offer %>

    <br>

    <div class="d-flex justify-content-center">
      <%= link_to "Mostrar", @job_offer, class: "btn btn-outline-warning me-3" %>
      <%= link_to "Ver más ofertas laborales", job_offers_path, class: "btn btn-outline-primary" %>
    </div>
  </div>
  <div class="col-lg-3"></div>
</div>

app/views/job_offers/index.html.erb
<div class="row">
  <div class="col">
    <h1 class="my-5">Ofertas laborales</h1>
    <% if admin_user? %>
      <div class="d-flex justify-content-end">
        <%= link_to "Publicar nueva oferta", new_job_offer_path, class: "btn btn-outline-success mb-5" %>
      </div>
    <% end %>
    <div id="job_offers" class="row">
      <% @job_offers.reverse.each do |job_offer| %>
        <div class="col mb-4">
          <%= render job_offer %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/job_offers/new.html.erb
<div class="row">
  <div class="col-lg-3"></div>
  <div class="col-lg-6">
    <h2 class="mb-4">Publicar nueva oferta</h2>

    <%= render "form", job_offer: @job_offer %>

    <br>

    <div class="d-flex justify-content-center">
      <%= link_to "Ver más ofertas laborales", job_offers_path, class: "btn btn-outline-primary" %>
    </div>
  </div>
</div>

app/views/job_offers/show.html.erb
<div class="row">
  <div class="col-lg-3"></div>
  <div class="col-lg-6">
    <h2>Puesto: <%= @job_offer.job %></h2><br>
    <p style="font-size: 1.3rem;"><%= @job_offer.description %></p>
    <div class="border-bottom w-100 mb-4"></div>
    <% unless admin_user? %>
      <div class="d-flex justify-content-center">
        <%= button_to "POSTULAR", associate_job_offer_path(@job_offer), method: :post, class: "btn btn-primary" %>
      </div>
    <% end %>
    <% if admin_user? %>
      <div class="d-flex justify-content-end">
        <%= link_to "Editar", edit_job_offer_path(@job_offer), class: "btn btn-outline-warning me-3" %>
        <%= button_to "Borrar", @job_offer, method: :delete, class: "btn btn-outline-danger" %>
      </div><br><br>

      <h4 class="mb-4">Usuarios que postularon a este puesto</h4>
      <% if @job_offer.users.length == 0 %>
        <p>Ningún usuario ha postulado a este puesto.</p>
      <% else %>
        <% @job_offer.users.each_with_index do |user, i| %>
          <% if i != 0 %>
            <div class="border-top w-100"></div>
          <% end %>
          <div class="mb-3">
            <div class="d-flex align-items-center">
              <%= image_tag user.avatar, class: "rounded-circle m-2", style: "width: 50px;" %>
              <h5><%= user.name %></h5>
            </div>
            <p><%= user.about %></p>
            <div class="d-flex justify-content-center">
              <p style="font-size: 18px" class="me-4"><i class="fa-solid fa-envelope"></i> <%= user.email %></p>
              <p style="font-size: 18px"><i class="fa-solid fa-phone"></i> <%= user.phone %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>
  

app/views/job_offers/user_offers.html.erb
<div class="row">
    <div class="col">
        <h2 class="my-5">Mis postulaciones</h2>
        <div class="row">
            <% current_user.job_offers.each do |job_offer| %>
                <div class="col mb-4">
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">
                            <h3 class="card-title"><strong><%= job_offer.job %></strong></h3>
                            <p class="card-text"><%= job_offer.description %></p>
                            <div class="d-flex justify-content-end">
                                <%= link_to "Ver más", job_offer, class: "btn btn-primary" %>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>